### ISSUE TITLE
Not able to use custom image

### ISSUE THREAD

**Issue by felixkriechbaum** [MuhammadHassanRazaa/FlutterSocialLoginButtons#1]
Hi Muhammad,

When I try to load a CustomIcon with "imagePath" I always get the error that it tries to search for an icon in the package. If I have understood correctly, but should give the possibility to set a custom icon.

When i try:
![SCR-20221102-ww](https://user-images.githubusercontent.com/1184644/199362088-6e1c9555-fd48-4530-b7ae-dbbd78e607cf.png)

I get:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/1184644/199362232-436a3c72-ca81-4b64-9dc4-2b9f43eb633a.png">

Im using the actual version of FlutterSocialButtons(^1.0.6+2) and the actual version from Flutter
(
Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (7 days ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
)

**Comment by MuhammadHassanRazaa** [comment]
Hi,

Thanks for raising, Did you put assets in pubsec.yaml file?

**Comment by felixkriechbaum** [comment]
Yes i did:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/1184644/199464625-1bd08fab-4993-4957-9aeb-22643413c1b5.png">

**Comment by MuhammadHassanRazaa** [comment]
The Issue has been fixed in version [1.0.7](https://pub.dev/packages/social_login_buttons). Please try that version.

**Comment by felixkriechbaum** [comment]
Hi @MuhammadHassanRazaa,

its still not working, regarding the error the package use the package path to look for a image not the general i provide.

`
Image provider: AssetImage(bundle: null, name: "packages/social_login_buttons/assets/icons/twitter.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#97386(), name: "packages/social_login_buttons/assets/icons/twitter.png", scale: 1.0)
`

**Comment by felixkriechbaum** [comment]
Hi @MuhammadHassanRazaa,

its still not working, regarding the error the package use the package path to look for a image not the general i provide.

`
Image provider: AssetImage(bundle: null, name: "packages/social_login_buttons/assets/icons/twitter.png")

Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#97386(), name: "packages/social_login_buttons/assets/icons/twitter.png", scale: 1.0)
`

**Comment by felixkriechbaum** [comment]
and twitter is not twitter anymore, its X

**Comment by MuhammadHassanRazaa** [comment]
Hi,

Sorry this package is not maintained anymore. You may use https://pub.dev/packages/authentication_buttons
